services:
  pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: hakaton-kion
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # Переменные для кеша Hugging Face
      - HF_HOME=/app/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/app/cache/huggingface
      - TRANSFORMERS_CACHE=/app/cache/huggingface
      - TORCH_HOME=/app/cache/torch
      # Опционально: переменная для токена (если нужен доступ к закрытым моделям)
      # - HF_TOKEN=your_token_here
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./requirements.txt:/app/requirements.txt
      - ./config:/app/config
      - ./cache:/app/cache
      - ./src:/app/src
    shm_size: 16g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    working_dir: /app